### ISSUE TITLE
I have this error, help me pls with this

### ISSUE THREAD

**Issue by VVriter** [apet2929/Test_LWJGL#1]
> Task :Launcher.main() FAILED
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so
	at org.lwjgl.system.Library.loadSystem(Library.java:162)
	at org.lwjgl.system.Library.loadSystem(Library.java:62)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:41)
	at com.apet2929.core.EngineManager.init(EngineManager.java:26)
	at com.apet2929.core.EngineManager.start(EngineManager.java:36)
	at com.apet2929.test.Launcher.main(Launcher.java:20)

Execution failed for task ':Launcher.main()'.
> Process 'command '/home/administrator/.jdks/corretto-11.0.15/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by apet2929** [comment]
Did you end up fixing it? If not, what I would do is create a new project according to the Getting Started page on LWJGL, and copy over all the files by hand from my repo which you want to use. Hope this helps.
